### ISSUE TITLE
Small change in floating point exponentiation causes a test failure on Julia 1.8.

### ISSUE THREAD

**Issue by KristofferC** [MineralsCloud/EquationsOfStateOfSolids.jl#146]
From the PkgEval log at https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/9b7990d_vs_8611a64/EquationsOfStateOfSolids.primary.log it shows this package has a test failure on the upcoming Julia 1.8 release.

I looked at it a little bit and it seems that a small precision change to floating point power is causing the problem. The test that errors is at

https://github.com/MineralsCloud/EquationsOfStateOfSolids.jl/blob/3d9cc316766648d6fd287941699dc502265db058/test/Fitting.jl#L650-L654

If we print out `v0_prev` and `v0` we can see that it just oscillates back and forth:

```jl
(v0_prev, v0) = (19.361802843683524, 19.36180284371997)
(v0_prev, v0) = (19.36180284371997, 19.361802843683524)
(v0_prev, v0) = (19.361802843683524, 19.36180284371997)
(v0_prev, v0) = (19.36180284371997, 19.361802843683524)
(v0_prev, v0) = (19.361802843683524, 19.36180284371997)
(v0_prev, v0) = (19.36180284371997, 19.361802843683524)
(v0_prev, v0) = (19.361802843683524, 19.36180284371997)
(v0_prev, v0) = (19.36180284371997, 19.361802843683524)
(v0_prev, v0) = (19.361802843683524, 19.36180284371997)
(v0_prev, v0) = (19.36180284371997, 19.361802843683524)
```

and the convergence criteria is never satisfied.  So it seems this algorithm used here need to be a bit more robust to handle cases like this. 

The difference in the result comes from:

```jl
S = EquationsOfStateOfSolids.FiniteStrains.EulerianStrain
volumes = ([17.789658, 18.382125, 18.987603, 19.336585, 19.606232, 20.238155, 20.883512])
v0 = 19.361802843683524
strains = map(EquationsOfStateOfSolids.FiniteStrains.ToStrain{S}(v0), volumes)
```

On 1.7:

```jl
julia> strains[1]
0.029040354449144212
```

On 1.8:

```jl
 julia> strains[1]
0.029040354449144323
```

**Comment by singularitti** [comment]
Thanks @KristofferC! I will be looking into it.

**Comment by singularitti** [comment]
Hi @KristofferC, I am using v1.8-beta3 on macOS 12. And the returned result is `0.029040354449144212`. Is the bug fixed in v1.8-beta3?

**Comment by KristofferC** [comment]
I still get `0.029...323`:

```
julia> VERSION
v"1.8.0-beta3"

julia> using EquationsOfStateOfSolids

julia> S = EquationsOfStateOfSolids.FiniteStrains.EulerianStrain
EquationsOfStateOfSolids.FiniteStrains.EulerianStrain

julia> volumes = ([17.789658, 18.382125, 18.987603, 19.336585, 19.606232, 20.238155, 20.883512]);

julia> v0 = 19.361802843683524;

julia> strains = map(EquationsOfStateOfSolids.FiniteStrains.ToStrain{S}(v0), volumes)
7-element Vector{Float64}:
  0.029040354449144323
  0.017610872272447953
  0.006547805447474242
  0.0004346228585491163
 -0.004164319971901476
 -0.014540219904364826
 -0.024593798606209416
```

But the tests no longer seem to error so, 🤷

**Comment by singularitti** [comment]
OK, I added [a test](https://github.com/MineralsCloud/EquationsOfStateOfSolids.jl/blob/b6ca0b02e1c97842e4fe8ccc0aeeac825134c0ea/test/FiniteStrains.jl#L8-L14) of it, and it does seem to happen on Linux (but works on macOS and 32-bit Windows). Could you inform me what the change is? I'm not sure what's causing this.

**Comment by KristofferC** [comment]
I'm surprised it is different on different OS. I think  https://github.com/JuliaLang/julia/pull/42271 changed this. I think I get the same result on linux and mac though, for example:

```jl
julia> f(v0, v) = ((v0 / v)^(2/3) - 1) / 2

julia> v0 = 19.361802843683524

julia> v = 17.789658

julia> f(v0, v)
0.029040354449144323

julia> Sys.isapple()
true

julia> VERSION
v"1.8.0-beta3"
```

**Comment by singularitti** [comment]
Interesting, I am using an M1 Pro Mac, so it gives me:

```julia-repl
julia> f(v0, v) = ((v0 / v)^(2/3) - 1) / 2
f (generic function with 1 method)

julia> v0 = 19.361802843683524
19.361802843683524

julia> v = 17.789658
17.789658

julia> f(v0, v)
0.029040354449144212

julia> Sys.isapple()
true

julia> VERSION
v"1.8.0-beta3"

julia> versioninfo()
Julia Version 1.8.0-beta3
Commit 3e092a2521 (2022-03-29 15:42 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: 10 × Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, westmere)
  Threads: 1 on 10 virtual cores
```

Does it depend on architecture?

**Comment by oscardssmith** [comment]
yeah. `exp` (and therefore `pow`) can give slightly different results for platforms without `fma`.
